version: '3.9'

services:
  django:
    container_name: django
    build:
      dockerfile: compose/django/Dockerfile
      context: .

    ports:
      - "8000:8000"

    volumes:
      - .:/app
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tenants_proj
      - DB_HOST=postgres
      - DB_PORT=5432

    depends_on:
      - postgres

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenants_proj
    ports:
      - "5432:5432"
    volumes:
      - tenants_postgres_data:/var/lib/postgresql/data

volumes:
  tenants_postgres_data:
